# Form implementation generated from reading ui file 'options.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import multiprocessing

class Ui_OptionsWindow(object): 

    def __init__(self, attack_options):
        super().__init__()
        #Default values if user does not change options
        self.core_count = 1
        self.pass_phrase_len = 10
        self.max_brute_force = 5
        self.attack_options = attack_options
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(294, 363)
        self.OptionsGroup = QtWidgets.QGroupBox(Form)
        self.OptionsGroup.setGeometry(QtCore.QRect(10, 10, 271, 341))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.OptionsGroup.setFont(font)
        self.OptionsGroup.setObjectName("OptionsGroup")
        self.processLbl = QtWidgets.QLabel(self.OptionsGroup)
        self.processLbl.setGeometry(QtCore.QRect(20, 30, 81, 21))
        self.processLbl.setObjectName("processLbl")
        self.processCountSpin = QtWidgets.QSpinBox(self.OptionsGroup)
        self.processCountSpin.setGeometry(QtCore.QRect(20, 60, 81, 21))
        self.processCountSpin.setObjectName("processCountSpin")
        self.passphraseLengthLbl = QtWidgets.QLabel(self.OptionsGroup)
        self.passphraseLengthLbl.setGeometry(QtCore.QRect(20, 80, 211, 31))
        self.passphraseLengthLbl.setObjectName("passphraseLengthLbl")
        self.passphraseMaxLenSpin = QtWidgets.QSpinBox(self.OptionsGroup)
        self.passphraseMaxLenSpin.setGeometry(QtCore.QRect(20, 120, 81, 21))
        self.passphraseMaxLenSpin.setObjectName("passphraseMaxLenSpin")
        self.maxBruteForceLenLbl = QtWidgets.QLabel(self.OptionsGroup)
        self.maxBruteForceLenLbl.setGeometry(QtCore.QRect(20, 150, 211, 31))
        self.maxBruteForceLenLbl.setObjectName("maxBruteForceLenLbl")
        self.bruteForceMaxSpin = QtWidgets.QSpinBox(self.OptionsGroup)
        self.bruteForceMaxSpin.setGeometry(QtCore.QRect(20, 190, 81, 21))
        self.bruteForceMaxSpin.setObjectName("bruteForceMaxSpin")
        self.applyOptionsBtn = QtWidgets.QPushButton(self.OptionsGroup)
        self.applyOptionsBtn.setGeometry(QtCore.QRect(10, 300, 251, 31))
        self.applyOptionsBtn.setObjectName("applyOptionsBtn")

        self.applyOptionsBtn.clicked.connect(self._save)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def _save(self):
        self.process_value = self.processCountSpin.value()
        self.passphrase_value = self.passphraseMaxLenSpin.value()
        self.bruteforce_value = self.bruteForceMaxSpin.value() 

        self.max_cpu = multiprocessing.cpu_count()

        #Set default values if user does not input
        if(self.process_value == 0):
            self.attack_options.core_count = self.core_count
        elif(self.process_value > self.max_cpu):
            self.attack_options.core_count = self.max_cpu
        else:
            self.attack_options.core_count  = self.process_value

        if(self.passphrase_value == 0):
            self.attack_options.pass_phrase_len = self.pass_phrase_len
        else:
            self.attack_options.pass_phrase_len  = self.passphrase_value

        if(self.passphrase_value == 0):
            self.attack_options.max_brute_force = self.max_brute_force
        else:
            self.attack_options.max_brute_force  = self.bruteforce_value
    


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowIcon(QtGui.QIcon('logo.png'))
        Form.setWindowTitle(_translate("Form", "Attack Options"))
        self.OptionsGroup.setTitle(_translate("Form", "Options"))
        self.processLbl.setText(_translate("Form", "Processes:"))
        self.passphraseLengthLbl.setText(_translate("Form", "Passphrase MAX Length:"))
        self.maxBruteForceLenLbl.setText(_translate("Form", "Max Brute Force length"))
        self.applyOptionsBtn.setText(_translate("Form", "Apply"))

